language: ruby
addons:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-13-postgis-3
services:
  - postgresql
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - sudo service postgresql@13-main restart
before_script:
  - sudo psql -p 5433 -U postgres -c 'create database my-app;'
  - nvm install --lts
